language: python

cache:
  directories:
  - $HOME/nats-server

python:
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - bash ./scripts/install_nats.sh

before_script:
  - export PATH=$HOME/nats-server:$PATH

install:
  - pip install -e .[nkeys,aiohttp,fast-mail-parser]

script:
  - make ci
  
notifications:
  email: false

sudo: true
dist: jammy

jobs:
  include:
  - name: "Python: 3.12"
    python: "3.12-dev"
    before_install:
      - sudo apt update && sudo apt install gcc build-essential -y
      - sudo apt-get install python3-pip
      - sudo apt-get install python3-pytest
      - pip install --upgrade pip
      - bash ./scripts/install_nats.sh
    install:
      - pip install -e .[fast-mail-parser]
  - name: "Python: 3.11"
    python: "3.11"
    before_install:
      - sudo apt update && sudo apt install gcc build-essential -y
      - sudo apt-get install python3-pip
      - sudo apt-get install python3-pytest
      - pip install --upgrade pip
      - bash ./scripts/install_nats.sh
    install:
      - pip install -e .[fast-mail-parser]
  - name: "Python: 3.11/uvloop"
    python: "3.11"
    before_install:
      - sudo apt update && sudo apt install gcc build-essential -y
      - sudo apt-get install python3-pip
      - sudo apt-get install python3-pytest
      - pip install --upgrade pip
      - bash ./scripts/install_nats.sh
    install:
      - pip install -e .[fast-mail-parser]
      - pip install uvloop
  - name: "Python: 3.11 (nats-server@main)"
    python: "3.11"
    env:
    - NATS_SERVER_VERSION=main
    before_install:
      - sudo apt update && sudo apt install gcc build-essential -y
      - sudo apt-get install python3-pip
      - sudo apt-get install python3-pytest
      - pip install --upgrade pip
      - bash ./scripts/install_nats.sh
    install:
      - pip install -e .[fast-mail-parser]
  - name: "Python: 3.11 (nats-server@dev)"
    python: "3.11"
    env:
    - NATS_SERVER_VERSION=dev
    before_install:
      - sudo apt update && sudo apt install gcc build-essential -y
      - sudo apt-get install python3-pip
      - sudo apt-get install python3-pytest
      - pip install --upgrade pip
      - bash ./scripts/install_nats.sh
    install:
      - pip install -e .[fast-mail-parser]
  - name: "Python: 3.7"
    python: "3.7"
    before_install:
      - sudo apt update && sudo apt install gcc build-essential -y
      - sudo apt-get install python3-pip
      - sudo apt-get install python3-pytest
      - pip install --upgrade pip
      - bash ./scripts/install_nats.sh
    install:
      - pip install -e .[aiohttp,fast-mail-parser]
    script:
      - pytest -vv -s --continue-on-collection-errors tests
  allow_failures:
    - name: "Python: 3.7"
    - name: "Python: 3.8"
    - name: "Python: 3.11"
    - name: "Python: 3.11/uvloop"
    - name: "Python: 3.11 (nats-server@dev)"
    - name: "Python: 3.12"
